AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

# Cops that are disabled by default

# Rails (not a rails app)
# Rails/SaveBang (not a rails app)

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Copyright:
  Enabled: true
  Notice: 'Copyright \(c\) 2016 Scott O.Hara, oharagroup.net'

# Style/DocumentationMethod (disabled due to no documentation)

Style/Encoding:
  Enabled: true

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstMethodParameterLineBreak:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

# Style/InlineComment (disabled due to use of inline comments)
# Style/MethodCallWithArgsParentheses (prefer no parens)

Style/MethodCalledOnDoEndBlock:
  Enabled: true

# Style/MissingElse (else not required)

Style/MultilineAssignmentLayout:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

# END disabled by default cops

# Block comment in spec_helper
Style/BlockComments:
  Enabled: false

# Needed for @@db
Style/ClassVars:
  Enabled: false

# Changed from 2 (spaces) to 1 (tab)
Style/IndentationWidth:
  Width: 1

# Only require parens where absolutely necessary
Style/NestedParenthesizedCalls:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Prefer tabs over spaces
Style/Tab:
  Enabled: false

# Disable metrics
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
