require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-config-oharagroup:
    - default.yml
    - performance.yml
    - rake.yml
    - rspec.yml

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"

# Needed for @@db
Style/ClassVars:
  Enabled: false
