require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rubocop-config-oharagroup:
    - default.yml
    - performance.yml
    - rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Needed for @@db
Style/ClassVars:
  Enabled: false