name: Build

on:
  push:
    tags: "*"

env:
  # CodeClimate only shows coverage for the default branch
  # As this action is only triggered by tags, assume the branch is 'master'
  GIT_BRANCH: master
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  setup:
    name: Setup test coverage reporting
    runs-on: ubuntu-latest

    steps:
    - name: Download CodeClimate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: Notify CodeClimate of a pending report
      run: ./cc-test-reporter before-build

  frontend:
    name: Test and lint frontend
    needs: setup
    runs-on: macOS-latest

    steps:
    - name: Create and boot iOS simulator
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
        DEVICE_TYPE_ID: com.apple.CoreSimulator.SimDeviceType.iPhone-X
        RUNTIME_ID: com.apple.CoreSimulator.SimRuntime.iOS-13-1
      run: |
        DEVICE_ID=$(xcrun simctl create tvm-simulator $DEVICE_TYPE_ID $RUNTIME_ID)
        xcrun simctl boot $DEVICE_ID

    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Delete npm prefix
      run: npm config delete prefix

    - name: Install dependencies
      shell: bash --login {0}
      run: nvm use && npm ci

    - name: Lint and test
      shell: bash --login {0}
      run: nvm use && npm test

    - name: Upload test coverage artifact
      uses: actions/upload-artifact@v1
      with:
        name: lcov.info
        path: coverage/frontend/lcov.info

  backend:
    name: Lint and test backend
    needs: setup
    runs-on: ubuntu-latest
    env:
      TVMANAGER_COUCHDB_URL: http://localhost:5984/tvm

    services:
      postgres:
        image: couchdb:latest
        ports:
        - 5984:5984

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install rvm
      shell: bash --login {0}
      run: |
        gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        curl -sSL https://get.rvm.io | bash -s stable
        echo "export rvm_install_on_use_flag=1" >> "$HOME/.rvmrc"
        echo "source $HOME/.rvm/scripts/rvm" >> "$HOME/.bash_profile"

    - name: Update to latest rubygems and bundler
      shell: bash --login {0}
      run: |
        echo "gem: --no-document" >> "$HOME/.gemrc"
        gem update --system
        gem install bundler

    - name: Install dependencies
      shell: bash --login {0}
      run: bundle install --without production --path=vendor/bundle

    - name: Setup database
      shell: bash --login {0}
      run: bundle exec rake db:migrate

    - name: Lint
      shell: bash --login {0}
      run: bundle exec rubocop -ESP

    - name: Test
      shell: bash --login {0}
      run: bundle exec rake spec

    - name: Upload test coverage artifact
      uses: actions/upload-artifact@v1
      with:
        name: .resultset.json
        path: coverage/backend/.resultset.json

  report:
    name: Send coverage report to CodeClimate
    needs: [frontend, backend]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Download CodeClimate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: Download frontend test coverage artifact
      uses: actions/download-artifact@v1
      with:
        name: lcov.info
        path: coverage/frontend

    - name: Download backend test coverage artifact
      uses: actions/download-artifact@v1
      with:
        name: .resultset.json
        path: coverage/backend

    - name: Format backend coverage
      run: ./cc-test-reporter format-coverage --input-type simplecov --output coverage/codeclimate.backend.json coverage/backend/.resultset.json

    - name: Format frontend coverage
      run: ./cc-test-reporter format-coverage --input-type lcov --output coverage/codeclimate.frontend.json --prefix /Users/runner/runners/2.159.2/work/tvmanager/tvmanager coverage/frontend/lcov.info

    - name: Merge backend and frontend coverage
      run: ./cc-test-reporter sum-coverage --parts 2 coverage/codeclimate.*.json

    - name: Upload coverage report
      run: ./cc-test-reporter upload-coverage